### PR TITLE
additional public keys added to mesos instances

### PR DESCRIPTION
**Pull request by tjhunter**
2 features:
- MESOS_HOME is (was?) not set during deployment, its value is exported
- add the option to give additional public keys to be deployed in ~/.ssh/authroized_keys. I found it very useful to provide other people permissions to access the compute nodes for debugging purpose.

### CODE REVIEW

**Comment by mateiz** [comment]
I think your MESOS_HOME setting code doesn't actually do anything, because the export is only active during the SSH session that you run that in. Did you test it out? And what was the motivation behind it? All of the scripts that need to set MESOS_HOME already do as far as I know.

The other commit looks like a useful thing to have, but I have a few suggestions:
- Right now it looks like you want a file that lists multiple keys, one per line. Would it make more sense to pass in a list of files that each contain one key (people's id_rsa.pub files)?
- The help string of the command line option should say more about what the argument means (e.g. say that it's a file).
- Instead of using an SSH command to copy each file to each machine, it may be faster to add it to the master and then run /root/mesos-ec2/copy-dir /root/.ssh/authorized_keys on that machine. (I think this will copy only that file.)

**Comment by tjhunter** [comment]
I will clean up and resubmit this patch when the semester is over.

**Comment by tjhunter** [comment]
Hello Matei,
sorry for the delay. Here is a cleaned patch. Let me know what you think of it. This patch to mesos-ec2.py adds a command to deploy additional public keys to the master and the slaves.

**Comment by tjhunter** [comment]
Ooops, I did not mean to close it.

**Comment by mateiz** [comment]
Hey Tim,

This looks good, but I think the export MESOS_HOME stuff is unnecessary. It will only be active during that one SSH command (it does not save the environment variable across shell sessions. Did it fix some problem you were seeing?

**Comment by tjhunter** [comment]
The MESOS_HOME command need not be committed, I need to figure out how to cherry pick a patch. Do you want to cherry pick from my branch instead of pulling the branch?

**Pull request closed without merging**
