### PR TITLE
Andyk event history nowebui

### PR DESCRIPTION
**Pull request by andyk**
This branch adds basic event_history logging infrastructure. This code now factors in the changes recommended by Matei in a previous code review and many of the changes discussed in earlier iterations in issue #39. Next steps that we've already begun include:
1. Expanding the event history calls in master to include slaves being added, removed, lost etc. (should be straightforward)
2. Updates to the webui to show the event history (needs to be tested) using nice tables (and eventually graphs)
3. Updating the embedded http server to export all state as JSON via HTTP

### CODE REVIEW

**Comment by mateiz** [comment]
I looked at the newest version and have several comments. Unfortunately, there's no view in GitHub that gives you both a unified diff and the ability to comment on each line (you have to comment on each commit separately), so I'm going to post them here.

### test_event_history.cpp:
- Don't create files in /tmp. The TEST_WITH_WORKDIR macro will ensure that your test runs in an empty directory based on your test name that is located in `<build directory>/test_output`. This is where we want all files created by that test to go. Use relative paths and stay inside this directory. Also, since the directory will be guaranteed to be empty, there's no need to rm -rf.

### date_utils.hpp:
- It would be nice to rename currentDateTimeInMicros to currentDateInMicros to be more similar with the existing function currentDate (which also gets the time too). Also, you should document that these are microseconds since the UNIX epoch, since the other currentDate function returns something quite different (a string). 
- Maybe the mock helper methods (setMockDate and clearMockDate) should also take a time in micros.

### event_history.cpp:
- Why not provide default values to the configurator? That way it will print the defaults by itself.
- If you can't create the log directory, don't just turn off event history. This is indicative of a more serious problem with the user's setup (they want event logs but they have no log directory), so it should be a fatal error.

### event_history.hpp:
- What is operator() (string, string) for? It doesn't seem to be implemented anywhere.

### file_event_writer.cpp:
- Some of the log formats are inconsistent (e.g. don't have spaces around the commas).
- In general I'd prefer a format that is less "human friendly" but easier to parse, such as `<time> <eventtype> <key1>=<value1> <key2>=<value2>`. We'll also need to make this format future-friendly eventually.

### General:
- Maybe we talked about this before, but why does the master need to get an EventLogger passed to its constructor instead of creating one itself based on its configuration? (I just don't remember whether there was an issue with that).
- It would be good if event history was disabled altogether in "local" mode, since that's when we don't have a clear place to put the logs. You can do this by passing a bool local to EventLogger::registerOptions and having it register different default values depending on whether you're in local mode.
- There are still a few cases of inconsistent forwarding, such as `//` without a space after the slashes, or `for(` instead of `for (`.
- The tests aren't yet checking whether the events have been logged to files in the right format, right?

**Comment by andyk** [comment]
Hey Matei, I pushed an update to the branch ee1386d967cd35044534bd40df04f5ddfbfa65d6. I'll respond to your points inline:

### test_event_history.cpp:

<ul><li> Don't create files in /tmp. The TEST_WITH_WORKDIR macro will ensure that your test runs in an empty directory based on your test name that is located in `<build directory>/test_output`. This is where we want all files created by that test to go. Use relative paths and stay inside this directory. Also, since the directory will be guaranteed to be empty, there's no need to rm -rf.</li>
<ul><li><b>Response:</b> Ok, I've updated the tests, as you suggested, to account for this.
</ul></li></ul></li>


### date_utils.hpp:
<ul><li> It would be nice to rename currentDateTimeInMicros to currentDateInMicros to be more similar with the existing function currentDate (which also gets the time too). Also, you should document that these are microseconds since the UNIX epoch, since the other currentDate function returns something quite different (a string). 

<ul><li><b>Response:</b> I've renamed it to `currentDateInMicro` and updated the comments in the date_utils.*pp files but maybe we should do some renaming to make it more clear what the functions return. Perhaps `currentDateInMicroSinceEpoch()`?
</li></ul></li></ul>


<ul><li>Maybe the mock helper methods (setMockDate and clearMockDate) should also take a time in micros.
<ul><li><b>Response:</b> Since we don't want to make the name of the master annoyingly long, how would this higher granularity for the mockDate be helpful right now? It seems like it will be easy enough to add this later.
</ul></li></ul></li>

### event_history.cpp:

<ul><li>Why not provide default values to the configurator? That way it will print the defaults by itself.
<ul><li><b>Response:</b> Done.
</ul></li></ul></li>

<ul><li>If you can't create the log directory, don't just turn off event history. This is indicative of a more serious problem with the user's setup (they want event logs but they have no log directory), so it should be a fatal error.
<ul><li><b>Response:</b> Done.
</ul></li></ul></li>

### event_history.hpp:

<ul><li>What is operator() (string, string) for? It doesn't seem to be implemented anywhere.
<ul><li><b>Response:</b> This was left over from a past design, I removed it.
</ul></li></ul></li>

### file_event_writer.cpp:

<ul><li>Some of the log formats are inconsistent (e.g. don't have spaces around the commas).
<ul><li><b>Response:</b> I've tried to clean this up.
</ul></li></ul></li>

<ul><li>In general I'd prefer a format that is less "human friendly" but easier to parse, such as `<time> <eventtype> <key1>=<value1> <key2>=<value2>`. We'll also need to make this format future-friendly eventually.
<ul><li><b>Response:</b> I've moved to JSON for now, but I'm open to other suggestions too.
</ul></li></ul></li>

### General:

<ul><li>Maybe we talked about this before, but why does the master need to get an EventLogger passed to its constructor instead of creating one itself based on its configuration? (I just don't remember whether there was an issue with that).
<ul><li> <b>Response:</b> I did this so that it fits into the dependency injection model we have been using for the master daemon, and so will make testing easier once I get to writing the test cases for event history logging in the master.
</ul></li></ul></li>
<ul><li>It would be good if event history was disabled altogether in "local" mode, since that's when we don't have a clear place to put the logs. You can do this by passing a bool local to EventLogger::registerOptions and having it register different default values depending on whether you're in local mode.
<ul><li><b>Response:</b> Good idea. I had something like this before, but I was doing it in the constructor and using instance data members to store the options (and so I wasn't able to include the defaults in addOptions(). Based on your suggestion, I've updated it so that now EventLogger::registerOptions(Configurator*) can optionally accept values to be used as defaults for the (currently) two conf options. This way a user of EventLogger calling addOptions can choose to override the default-defaults (as local.cpp now does) or use those selected by the creator of the event_history code (as the master/main.cpp still does, which is how it was before).
</ul></li></ul></li>

<ul><li>There are still a few cases of inconsistent forwarding, such as `//` without a space after the slashes, or `for(` instead of `for (`.
<ul><li><b>Response:</b> I think I've cleaned them all up now. Let me know if I missed any.</ul></li></ul></li>

<ul><li>The tests aren't yet checking whether the events have been logged to files in the right format, right?
<ul><li><b>Response:</b> Correct, I plan on writing those in the future.
</ul></li></ul></li>

**Comment by andyk** [comment]
I've made some changes that Matei suggested to better integrate my currentDateInMicros() into the structure of DateUtils, and I've added two tests for date_utils. I think this may be ready to merge into master?

**Comment by andyk** [comment]
Commit 8ab692f11f9e9dbb8a487c704c865d20542233b7 addresses this issue, though I'm not sure if it closes it.

**Pull request merged**
